[2023-11-02T10:56:30.173+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [queued]>
[2023-11-02T10:56:30.187+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [queued]>
[2023-11-02T10:56:30.188+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:56:30.189+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-02T10:56:30.189+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T10:56:30.221+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2020-04-08 00:00:00+00:00
[2023-11-02T10:56:30.228+0000] {standard_task_runner.py:55} INFO - Started process 1632 to run task
[2023-11-02T10:56:30.231+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag_tutorial', 'create_postgres_table', 'scheduled__2020-04-08T00:00:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_tutorial.py', '--cfg-path', '/tmp/tmpgqrk5uev']
[2023-11-02T10:56:30.232+0000] {standard_task_runner.py:83} INFO - Job 313: Subtask create_postgres_table
[2023-11-02T10:56:30.465+0000] {task_command.py:376} INFO - Running <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [running]> on host 1dfdc0df4852
[2023-11-02T10:56:30.617+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tetiana
AIRFLOW_CTX_DAG_ID=test_dag_tutorial
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2020-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-08T00:00:00+00:00
[2023-11-02T10:56:30.669+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-02T10:56:30.671+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-11-02T10:56:30.686+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=test_dag_tutorial, task_id=create_postgres_table, execution_date=20200408T000000, start_date=20231102T105630, end_date=20231102T105630
[2023-11-02T10:56:30.724+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 313 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 1632)
[2023-11-02T10:56:30.745+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-11-02T10:56:30.829+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-02T11:05:37.481+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [queued]>
[2023-11-02T11:05:37.508+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [queued]>
[2023-11-02T11:05:37.514+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T11:05:37.514+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-11-02T11:05:37.515+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-02T11:05:37.553+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2020-04-08 00:00:00+00:00
[2023-11-02T11:05:37.562+0000] {standard_task_runner.py:55} INFO - Started process 2257 to run task
[2023-11-02T11:05:37.563+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag_tutorial', 'create_postgres_table', 'scheduled__2020-04-08T00:00:00+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_tutorial.py', '--cfg-path', '/tmp/tmpatv9jc66']
[2023-11-02T11:05:37.564+0000] {standard_task_runner.py:83} INFO - Job 421: Subtask create_postgres_table
[2023-11-02T11:05:37.772+0000] {task_command.py:376} INFO - Running <TaskInstance: test_dag_tutorial.create_postgres_table scheduled__2020-04-08T00:00:00+00:00 [running]> on host 1dfdc0df4852
[2023-11-02T11:05:38.022+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tetiana
AIRFLOW_CTX_DAG_ID=test_dag_tutorial
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2020-04-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-08T00:00:00+00:00
[2023-11-02T11:05:38.083+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-02T11:05:38.091+0000] {sql.py:315} INFO - Running statement: 
        create table if not exists dag_runs (
        dt date,
        dag_id character varying,
        primary key(dt, dag_id)

        )
        , parameters: None
[2023-11-02T11:05:38.103+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2023-11-02T11:05:38.140+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=test_dag_tutorial, task_id=create_postgres_table, execution_date=20200408T000000, start_date=20231102T110537, end_date=20231102T110538
[2023-11-02T11:05:38.216+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-02T11:05:38.259+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
